In [1]:
import tensorflow as tf

In [2]:
x = [[1, 2],
     [3, 4]]
m = tf.matmul(x, x)
print(m)

Tensor("MatMul:0", shape=(2, 2), dtype=int32)


In [3]:
with tf.Session() as sess:
    print(sess.run(m))

[[ 7 10]
 [15 22]]


### Restart Kernel

In [1]:
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
tf.executing_eagerly()

True

In [3]:
x = [[1, 2],
     [3, 4]]
m = tf.matmul(x, x)
print(m)

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


In [4]:
print(m.numpy())

[[ 7 10]
 [15 22]]
